[project]
name = "05-custom-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "pydantic>=2.11.7",
    "strands-agents>=1.0.0",
    "uvicorn[standard]>=0.35.0",
]
